package com.gb.common.model.po;

public class Good {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.id
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.name
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.price
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.image
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.description
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.stock
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.id
     *
     * @return the value of good.id
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.id
     *
     * @param id the value for good.id
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.name
     *
     * @return the value of good.name
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.name
     *
     * @param name the value for good.name
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.price
     *
     * @return the value of good.price
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.price
     *
     * @param price the value for good.price
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.image
     *
     * @return the value of good.image
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.image
     *
     * @param image the value for good.image
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.description
     *
     * @return the value of good.description
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.description
     *
     * @param description the value for good.description
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.stock
     *
     * @return the value of good.stock
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.stock
     *
     * @param stock the value for good.stock
     *
     * @mbggenerated Thu May 16 12:44:30 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}