package com.gb.common.model.po;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.name
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.address
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.phone
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.description
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.url
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.user_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.good_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private Integer goodId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.name
     *
     * @return the value of store.name
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.name
     *
     * @param name the value for store.name
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.address
     *
     * @return the value of store.address
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.address
     *
     * @param address the value for store.address
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.phone
     *
     * @return the value of store.phone
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.phone
     *
     * @param phone the value for store.phone
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.description
     *
     * @return the value of store.description
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.description
     *
     * @param description the value for store.description
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.url
     *
     * @return the value of store.url
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.url
     *
     * @param url the value for store.url
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.user_id
     *
     * @return the value of store.user_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.user_id
     *
     * @param userId the value for store.user_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.good_id
     *
     * @return the value of store.good_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.good_id
     *
     * @param goodId the value for store.good_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }
}