package com.gb.common.model.po;

public class Town {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.name
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.address
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.phone
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.type
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.pic
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.introduction
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.max_person
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private Integer maxPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.image
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.url
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.user_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.id
     *
     * @return the value of town.id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.id
     *
     * @param id the value for town.id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.name
     *
     * @return the value of town.name
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.name
     *
     * @param name the value for town.name
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.address
     *
     * @return the value of town.address
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.address
     *
     * @param address the value for town.address
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.phone
     *
     * @return the value of town.phone
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.phone
     *
     * @param phone the value for town.phone
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.type
     *
     * @return the value of town.type
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.type
     *
     * @param type the value for town.type
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.pic
     *
     * @return the value of town.pic
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.pic
     *
     * @param pic the value for town.pic
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.introduction
     *
     * @return the value of town.introduction
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.introduction
     *
     * @param introduction the value for town.introduction
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.max_person
     *
     * @return the value of town.max_person
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public Integer getMaxPerson() {
        return maxPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.max_person
     *
     * @param maxPerson the value for town.max_person
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setMaxPerson(Integer maxPerson) {
        this.maxPerson = maxPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.image
     *
     * @return the value of town.image
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.image
     *
     * @param image the value for town.image
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.url
     *
     * @return the value of town.url
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.url
     *
     * @param url the value for town.url
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.user_id
     *
     * @return the value of town.user_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.user_id
     *
     * @param userId the value for town.user_id
     *
     * @mbggenerated Thu May 16 02:30:09 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}